apiVersion: v1
kind: Service 
metadata:
  name: taskops-mongodb-service
  labels:
    app: taskops-app
spec:
  type: ClusterIP
  selector:
    app: taskops-app
    component: mongodb
  ports:
    - port: 27017
      targetPort: 27017
