{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskops-api-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: taskops-app
    component: api
spec:
  selector:
    matchLabels:
      app: taskops-app
      component: api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
{{- end }}